channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- python>=3.11,<3.13
- pip
- numpy=1.26.4
- ase=3.27.0
- pymatgen=2026.5.4
- pyiron_workflow=0.15.6
- pyiron_lammps=0.5.4
- pandas=3.0.0
- scipy=1.17.0
- matplotlib=3.10.9
- scikit-learn=1.8.0
- tqdm=4.67.3
- lammps=2024.08.29
- pysqa=0.4.0
- pip:
  - pyiron-workflow-atomistics==0.0.7
  - pyiron-snippets==1.2.1
  - lz-GB-code==0.1.0
