name: Release

on:
#  pull_request:
  release:
    types: [ published ]

jobs:
  pyiron:
    uses: ./.github/workflows/pyproject-release.yml
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      lower-bound-yaml: '.ci_support/lower-bound.yml'
      pypi-to-conda-name-map-file: '.github/actions/.support/pypi_vs_conda_names.json'
      